Add fallback configuration for NetworkManager
RevolutionPi/imagebakery pull request #107
Opened 2023-05-10 20:52 UTC by nbuchwitz

2023-05-10 21:38 UTC, naruxde requested changes
Didn't you want so set the permissions to 600 of the .nmconnection files? I think you told me that's important.

2023-05-11 06:27 UTC, iluminat23 requested changes

2023-05-11 06:27 UTC, iluminat23 commented on customize_image.sh
> +cp "$BAKERYDIR/templates/network-manager/fallback-dhcp.nmconnection" "$IMAGEDIR/etc/NetworkManager/system-connections"
Use [install](https://www.man7.org/linux/man-pages/man1/install.1.html) instead of cp

2023-05-11 09:24 UTC, naruxde approved these changes

2023-05-11 09:28 UTC, nbuchwitz commented
I've updated the PR and also moved the config file for unmanaged interfaces on PiBridge to the template folder.

2023-05-11 09:35 UTC, naruxde approved these changes

2023-05-11 09:45 UTC, iluminat23 approved these changes

2023-05-11 10:11 UTC, merged