set default language to en_US.UTF-8
RevolutionPi/imagebakery pull request #25
Opened 2021-03-05 15:59 UTC by pavlic244

As we have set the default keyboard to us we should also
set the default language to en_US.UTF-8. We need to set
and configure it immediately to avoid setlocale warnings
during the image build.

Signed-off-by: Frank Pavlic <f.pavlic@kunbus.com>

2021-03-09 15:27 UTC, iluminat23 requested changes

2021-03-09 15:27 UTC, iluminat23 commented on customize_image.sh
> +echo 'LC_ALL="en_US.UTF-8"' >> $IMAGEDIR/etc/default/locale
This is what a new clean Debian installation shows me:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

2021-03-10 08:12 UTC, zhan-kunbus commented
I thought once the command "locale-gen" can be used to generate the locale "us", and thus the command "dpkg-reconfigure -fnoninteractive locales" is not needed, to avoid the warning which might be caused by the incompatibility between qemu and locale

2021-03-10 08:14 UTC, iluminat23 approved these changes

2021-03-10 08:16 UTC, merged