install dt-blob.bin from revpi-dt-blob.dtbo
RevolutionPi/imagebakery pull request #79
Opened 2022-09-15 11:52 UTC by zhan-kunbus

For CM3 and CM4S the pin configuration of HAT EEPROM is contained in revpi-dt-blob-overlay.dts, and in generated revpi-dt-blob.dtbo. This should be used for the first booting with HAT EEPROM to recongnize it well.

The dt-blob.bin is the right file for this purpose, as it will be loaded by vc core and get applied for the kernel.

Signed-off-by: Zhi Han <z.han@kunbus.com>

2022-09-15 12:40 UTC, iluminat23 requested changes
The commit message doesn't make any sense form me.
It is some what backwards, contains information which is irrelevant and missing important information as well.
It is not really important in this case that the file is compiled from `revpi-dt-blob-overlay.dts`. It is not totally wrong to contain such information to understand why this change is done.
It is unclear why this is necessary. It starts of with something about CM3 and CM4S , but then fells short about providing any understandable information.

First describe the problem you are trying to solve. Then describe the solution that is done with your change.

2022-09-15 13:45 UTC, zhan-kunbus commented
> The commit message doesn't make any sense form me. It is some what backwards, contains information which is irrelevant and missing important information as well. It is not really important in this case that the file is compiled from `revpi-dt-blob-overlay.dts`. It is not totally wrong to contain such information to understand why this change is done. It is unclear why this is necessary. It starts of with something about CM3 and CM4S , but then fells short about providing any understandable information.
> 
> First describe the problem you are trying to solve. Then describe the solution that is done with your change.

The detail (reasons and how) of the Pin configuration should maybe belong to the commit of revpi-dt-blob-overlay.dts.  Here as it just build the image, too much detailed information should not be put in. However, if you could suggest a good commit message from point of you, I am happy to take it.

2022-09-15 15:36 UTC, iluminat23 commented
I agree, that there is no details about the changes of the dt-blob are needed here. But it should be clear why the blob is added now.
I will not provide you with a commit message. Please try to redo the commit message. I gave you some pointers you could use.

2022-09-16 09:52 UTC, iluminat23 approved these changes
Nice commit message.It describes everything well.

2022-09-16 13:41 UTC, nbuchwitz approved these changes
LGTM

2022-09-16 13:52 UTC, merged