Devel/revpi 2756/collect source modification
RevolutionPi/imagebakery pull request #82
Opened 2022-10-31 12:48 UTC by zhan-kunbus

2022-10-31 14:40 UTC, nbuchwitz commented
Please also remove the following:
https://github.com/RevolutionPi/imagebakery/blob/916746fd69a0d59b69467658a4f56fad4b9ec201/collect_sources.sh#L79-L80
https://github.com/RevolutionPi/imagebakery/blob/916746fd69a0d59b69467658a4f56fad4b9ec201/collect_sources.sh#L55 (wiringpi)

Further could you please check if we can download the node red sources from https://github.com/node-red/
Same applies to nodes and server from erminas:
https://github.com/erminas/noderedrevpinodes-server
https://github.com/erminas/noderedrevpinodes-server

2022-11-02 08:23 UTC, zhan-kunbus commented
> Please also remove the following:
> 
> https://github.com/RevolutionPi/imagebakery/blob/916746fd69a0d59b69467658a4f56fad4b9ec201/collect_sources.sh#L79-L80
> 
> 
> https://github.com/RevolutionPi/imagebakery/blob/916746fd69a0d59b69467658a4f56fad4b9ec201/collect_sources.sh#L55
> 
> (wiringpi)

done

> Further could you please check if we can download the node red sources from https://github.com/node-red/ 

also the source package of nodejs included ?

> Same applies to nodes and server from erminas: https://github.com/erminas/noderedrevpinodes-server https://github.com/erminas/noderedrevpinodes-server

The packages are installed from revpi repo, and deb source package of this packages can be gotten from there, wouldn't it better to use it instead of erminas?
`pi@RevPi0110:~ $ apt source noderedrevpinodes-server
Reading package lists... Done
NOTICE: 'noderedrevpinodes-server' packaging is maintained in the 'Git' version control system at:
https://github.com/RevolutionPi/noderedrevpinodes-server.git
Please use:
git clone https://github.com/RevolutionPi/noderedrevpinodes-server.git
to retrieve the latest (possibly unreleased) updates to the package.
Need to get 18.3 kB of source archives.
Get:1 http://packages.revolutionpi.de buster/main noderedrevpinodes-server 1.0.4-1 (diff) [3,660 B]
Get:2 http://packages.revolutionpi.de buster/main noderedrevpinodes-server 1.0.4-1 (dsc) [2,055 B]
Get:3 http://packages.revolutionpi.de buster/main noderedrevpinodes-server 1.0.4-1 (tar) [12.6 kB]
Fetched 18.3 kB in 0s (96.3 kB/s)
dpkg-source: info: extracting noderedrevpinodes-server in noderedrevpinodes-server-1.0.4
dpkg-source: info: unpacking noderedrevpinodes-server_1.0.4.orig.tar.gz
dpkg-source: info: unpacking noderedrevpinodes-server_1.0.4-1.debian.tar.xz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying 0001-Remove-upstream-package-build-scripts.patch
`

2022-11-02 09:52 UTC, nbuchwitz commented
1) NodeRed sadly doesn't provide sources packages. Therefore our only option is to download the sources from GitHub
2) Please use our packages for the erminas stuff as this is installed in our image. There are minor issues with the packaging of Erminas, so we decided to package it by ourself

2022-11-02 10:49 UTC, zhan-kunbus commented
the node-red can be gotten from "https://github.com/node-red/node-red/archive//master.tar.gz" 
but it seems there are lots of "packages" named "node-*" installed by npm, which have no source package for them.

2022-11-02 11:00 UTC, nbuchwitz requested changes

2022-11-02 15:41 UTC, zhan-kunbus commented on collect_sources.sh
> +wget -O node-red.tar.gz https://github.com/node-red/node-red/archive//master.tar.gz
the installed version of node-red can be downloaded now.

And for the other packages of npm,  would it be fine to make just a tarball from /usr/lib/node_modules ? @nbuchwitz

2022-11-03 13:36 UTC, nbuchwitz commented on collect_sources.sh
> +wget -O node-red.tar.gz https://github.com/node-red/node-red/archive//master.tar.gz
Sounds reasonable, please do so.

2022-11-04 11:39 UTC, nbuchwitz approved these changes
LGTM

2022-11-07 14:09 UTC, merged