Add python3-libgpiod to package list [REVPI-2606]
RevolutionPi/imagebakery pull request #86
Opened 2022-11-04 12:09 UTC by RamiGspo

"python3-libgpiod" added to package list.

2022-11-04 12:11 UTC, nbuchwitz requested changes
should be in [min-debs-to-download](https://github.com/RevolutionPi/imagebakery/blob/master/min-debs-to-download), so the library is also used for our lite image

2022-11-04 14:04 UTC, nbuchwitz approved these changes
My fault, please also add python3-yaml and python3-schema as we will need this for the config parser

2022-11-07 08:29 UTC, iluminat23 submitted a review, later dismissed
What about this?
Add -libgpiod, python3-yaml and python3-schema to the package list

2022-11-07 09:22 UTC, nbuchwitz approved these changes

2022-11-07 09:46 UTC, iluminat23 approved these changes

2022-11-07 09:55 UTC, merged